export const APPROVE_ANSWER = "APPROVE_ANSWER";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const SHOW_ASSIGNMENT = "SHOW_ASSIGNMENT";
export const ASSIGNMENTS_FETCHED = "ASSIGNMENTS_FETCHED";